# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: polyproto
repo_url: https://github.com/polyphony-chat/polyproto
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - privacy
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - toc:
      permalink: true
      toc_depth: 3